### ISSUE TITLE
Can't create Quizzes

### ISSUE THREAD

**Issue by stefetrucki** [kevinsguides/yaquiz#1]
When accessing the Page   .../administrator/index.php?option=com_yaquiz&view=Yaquizzes

I get the error: .../administrator/components/com_yaquiz/src/Model/YaquizModel.php on line 57

So i can not create any quizzes so the component does not work for me.

**Comment by kevinsguides** [comment]
I was able to replicate this issue on PHP 7x, if you are able to change to PHP 8 or higher it should be resolved.
I will see if I can get it to work with PHP 7.

**Comment by kevinsguides** [comment]
I've fixed the function so it should work with older versions of PHP, hopefully this resolves the issue. Update to latest version and see.

**Comment by stefetrucki** [comment]
thank you so much for the quick fix, it is working now :)

sorry for not adding Server Information. i am using PHP 8.0.29
