### ISSUE TITLE
problem editing Categories

### ISSUE THREAD

**Issue by stefetrucki** [kevinsguides/yaquiz#5]
Whenever I try to edit a category i get the following error

     0 array_key_exists(): Argument #2 ($array) must be of type array, null given 

also in Category view of joomla.

As soon as I disable your extension everything works fine again.

I am running on Joomla! 5.0.2 Stable.

**Comment by kevinsguides** [comment]
I was unable to replicate this error. Can you please enable "System - Debug System" in Global Config and paste or screenshot the error. This should show me exactly what lines/files might be causing the issue.
Thanks

**Comment by stefetrucki** [comment]
![Screenshot 2024-02-10 193812](https://github.com/kevinsguides/yaquiz/assets/75590665/2696dfd1-60c0-4823-945b-82366b75f46b)

**Comment by kevinsguides** [comment]
[com_yaq_hfx_2024-02-14.zip](https://github.com/kevinsguides/yaquiz/files/14283049/com_yaq_hfx_2024-02-14.zip)
Can you please try installing this update and see if that resolves it

**Comment by stefetrucki** [comment]
![image](https://github.com/kevinsguides/yaquiz/assets/75590665/2fe7aa7d-6500-41b7-a1cf-e723f2ae98cc)
Sorry, still not working

But i installed your Extension on the same environment and the clean installation gave no error, so the issue might be on my side. Maybe one extension is bad or incompatible with your extension, or there was a problem on some update, the main core of the page runs since Joomla 1.5

I will test different scenarios and let you know, but right now it looks there is a problem with my installation.

**Comment by stefetrucki** [comment]
after a lot of testing i could not manage to find the issue

any new Joomla 4 or 5 installations works out of the box with all extensions installed i usually use

Any Version that was previously older than Joomla 4, so Joomla 3 or lower and was upgraded to Joomla 4 or 5 has this issue

maybe it is a problem with Joomla updating to Joomla 4 or i have a leftover of an old extension that makes this problem, which i was finding going through all files and db tables

i don't know any further and will stop the investigation for now, don't know what else I can try without reinstalling and copying each article individually to the new site :(

**Comment by kevinsguides** [comment]
That sounds annoying!
YaQuiz loosely uses Joomla's default category system but yeah, I still have no idea what's causing your issue. It could possibly be a php or mysql version issue... the little update I provided should have stopped the extension from sending anything to the category AssociationExtensionHelper... I know several people who use this extension in 4/5 with no issues. 🤷‍♂️ 
I'm not a super skilled Joomla developer yet so sorry I can't provide further help on this!
Hopefully you don't have too many articles but if you do there are other ways to export/import them from 3 to 4/5.
Good luck!

**Comment by stefetrucki** [comment]
HA, I just gave it another try and found the problem :) (or got closer to the solution)

as long as the extension "Multilingual Associations" is activated, YaQuiz gives me the bug. (multilanguage is configured)

On the fresh install I never activated multi language, and for now i do not want to investigate, because it makes no difference to me, because the page i want to use the extension, one language is fine for now.

best regards for the help :)
